### ISSUE TITLE
Usage with multiple cars linked to account

### ISSUE THREAD

**Issue by duracell** [g-mocken/ZoeStatus#6]
Hey, thank you for this App :)
There are currently 2 zoes attached to my account. In the (new) renault I can just switch between them on top.
But I couldn't find any information how I can switch between cars in the app, is this possible? Or at least define a default car on the phone/watch?

**Comment by g-mocken** [comment]
The current version simply takes the first VIN that it finds in the account, and this is hard coded for now (see MyR.swift, line 284: _result!.vehicleLinks[0].vin_) - mostly because I have only one car in my own account, and therefore I cannot test it with more than one.
It would not be very difficult to add an extra preference item (say: an index number 1, 2, 3 ... ) and then pick the specified one instead. However I would have to totally rely on you (and preferably a few more people) for testing (e.g. via Testflight).

**Comment by g-mocken** [comment]
As it turns out, it was a little more complicated than I anticipated, but nevertheless here's an experimental version with an additional setting [https://testflight.apple.com/join/lT0KBqzh] and display of the resulting VIN.

**Comment by duracell** [comment]
Wow, that was really fast! Great Job! <3
Testflight displays, that the app doesn't accept new testers, but will have a look later.

**Comment by g-mocken** [comment]
Yes, that error message is always confusing. The real problem is that the app has to go through a preliminary review on Apple's side. Just try again later.

**Comment by g-mocken** [comment]
It was approved, so the link should be active now.
