### ISSUE TITLE
VIN Index error

### ISSUE THREAD

**Issue by Dan3333333** [g-mocken/ZoeStatus#7]
I'm having a login issue with your iOS app: "Failed to login to MY.R. services (VIN index not found)".
Tried using any of VIN indexes (1 to 5) but without success.
Kamareon key used is: Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2 (the only one that works.
Even tried Testflight beta ....
Any idea what to do to fix it? I need a reliable MY R alternative.

Thanks!

**Comment by g-mocken** [comment]
If you have only one car in your MyR account, then index 1 is the one that should work. I will check the code whether this error message about the VIN index might result from a totally unrelated login problem.

The current TestFlight beta is identical to the current release version, so no difference is to be expected.

Regarding MyR reliability (especially regarding pre-conditioning, which you mentioned in your direct email): Any app depends on Renault's backend services, and they have a really bad track record. The pre-conditioning never worked reliably for me, which is why I have not extended my "ZE inter@ctive" subscription anymore.

**Comment by Dan3333333** [comment]
Thanks for the info! I have only one car but vin index 1 is not working (at least for me) :(….
The mountbatt’ script found here works flawlessly every time but want something that is usable on my watch like your app Zoe Status.
Thanks again and waiting for the fix (hope it’s possible)
Dan

Sent from my iPhone
________________________________

**Comment by Dan3333333** [comment]
forgot to add script's link : https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7

**Comment by g-mocken** [comment]
I briefly checked the code, only found
```
                                                                if self.vehicle >= result!.vehicleLinks.count {
                                                                    errorCode("VIN index not found.")
}
```
which basically compares the selected VIN index _minus one_ to the number of vehicles registered in your account. If it fails for VIN index 1, this suggests that you have zero vehicles in your account. Is that possible?
Then the ZOE-Widget.js script, which simply picks the first index without checking (like previous versions of ZoeStatus did) should not work either, though.
Assuming that there is exactly one vehicle in your account, then something must be wrong on the left hand side. Did you try deleting ZoeStatus and starting over from scratch (and do not touch VIN Index = 1 in the settings)?
Maybe it somehow got stuck at VIN index 2 or higher, although I cannot imagine how ...

**Comment by Dan3333333** [comment]
Tried that already (reinstalling the app).
Given that MYR displays my vehicle (only one) and sometimes works , plus ZOE-Widget.js working everytime there is something fishy with how ZOE Status is reading vehicle index in my account (I guess).
Maybe making a new version where you can unselect/disable  de VIN index setting (if you have one car, like me)?

Thanks!

**Comment by g-mocken** [comment]
The essence in that Javascript is:
```
if( VIN == "" ){
			// set VIN
			VIN = apiResult.vehicleLinks[0].vin
}
```
which means that it simply picks the first (array index 0) in case no VIN is given. 

What I do in Swift is to use as VIN the output of 

`result!.vehicleLinks.sorted(by: { $0.vin < $1.vin })[self.vehicle].vin
`

which gives exactly the same, if there is just one entry in the vehicleLinks array and if self.vehicle==0. I only sort the array by VIN before accessing it, because otherwise, it would be a random selection.

So I think the problem probably is something totally unrelated to this index/VIN. I am afraid there is no way to analyze this further until I find the time to put in some (optional) logging to automatically gather debug data (but without exposing any private data - that is the tricky bit here). Of course you are welcome to download and compile the source code (with Xcode on MacOS) yourself. When running the code with Xcode attached, there is a hell lot of logging information which would help to find the root of this issue.

Note that I myself have only one car, and I was relying on a few other people telling me that it now works for more than one as designed. So for me, every setting other than "1st VIN" results in the same error message (as designed).
